# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03fd8e05bf8a1ee497770be0764f5072a10290b8f527eeb96c40a6344be351b350d4e98eb45d012c0ec8eb3871ca89cac563e166a915021f783cd56ee02f7610

test:
  secret_key_base: 9cfeae52549db535cf13ff15073cdb1baa7765dc7e78e3330995220dc9e00f1aecacc4820612b9c353b3302576204731940c4961c3ba755ea4d3039b0b66f751

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["BDC_SECRET_KEY_BASE"] %>
  secret_token: <%= ENV["BDC_SECRET_TOKEN"] %>
